// Every answer refers only to details visible in the accompanying photograph.
// Condition options avoid claims about age, function, or hidden surfaces.
export const questions = [
  { id:3, room:'Bedroom', item:'Sofa seat cushion', description:['Dark blue fabric sofa seat cushion','Black leather sofa arm','Grey fitted carpet'], condition:['Visible pale marks on the fabric surface','No visible marks on the fabric','A torn seam at the rear edge'], explain:'The dark fabric cushion has several pale marks. The image cannot establish what caused them.' },
  { id:4, room:'Hallway', item:'Skirting board', description:['White painted skirting board above wood effect flooring','White ceramic wall tile above vinyl','Cream carpet beside a metal threshold'], condition:['No obvious damage visible in this view','Skirting board detached from the wall','Deep crack through the flooring'], explain:'This view shows a white skirting board and wood effect floor. No clear defect is visible here.' },
  { id:5, room:'Bedroom', item:'Fabric surface', description:['Dark fabric upholstered seat cushion','Black polished stone worktop','Dark ceramic floor tile'], condition:['Visible pale marks and disturbed pile across the surface','Completely unmarked surface','Broken corner and exposed foam'], explain:'There are visible marks across the dark fabric. Describe those, without inventing a cause.' },
  { id:6, room:'Kitchen', item:'Wall cupboard', description:['Dark-fronted wall cupboard with white interior shelves','White freestanding wardrobe with hanging rail','Open wooden bookcase'], condition:['No visible breaks on the photographed shelf surfaces','Middle shelf visibly broken','Door missing from the cupboard'], explain:'The open cupboard shows white shelves without visible breaks. Hinge operation needs a separate check.' },
  { id:8, room:'Ceiling', item:'Ceiling fitting', description:['Circular recessed ceiling vent','Pendant light with fabric shade','Wall-mounted smoke alarm'], condition:['No obvious damage visible to the fitting','Cover hanging loose from the ceiling','Visible water staining around the fitting'], explain:'It is a circular ceiling vent, with no obvious damage visible in the photo.' },
  { id:11, room:'Bedroom', item:'Wall and skirting', description:['White painted wall above dark skirting board','Grey tiled wall above a basin','Timber panelled wall above carpet'], condition:['Light marks visible on the wall near the lower section','Large hole through the wall','Skirting board visibly detached'], explain:'Light marks can be seen on the wall near the skirting. The photo does not show a hole.' },
  { id:13, room:'Bedroom', item:'Bedside unit', description:['White slatted bedside cabinet','Dark timber chest of drawers','Chrome framed glass side table'], condition:['No obvious damage visible to the top or front','Top split in two','One drawer front missing'], explain:'No damage is visible on the photographed top or front. Unseen sides remain unverified.' },
  { id:14, room:'Bathroom', item:'Wash basin area', description:['White basin beneath mirror on grey tiled wall','Stainless steel kitchen sink beneath window','Ceramic toilet beside a shower screen'], condition:['No obvious damage visible to the basin or surrounding tiles','Basin visibly cracked','Tiles missing above the basin'], explain:'The photo shows a white basin and grey wall tiles. No clear damage is visible to them.' },
  { id:15, room:'Bathroom', item:'Shower enclosure', description:['Glass shower screen against grey tiled walls','Opaque shower curtain on a plastic rail','Freestanding bath beside painted plaster'], condition:['No obvious damage visible to screen or tiles','Glass screen visibly shattered','Several wall tiles missing'], explain:'The glass screen and tiled walls are visible; neither shows an obvious break here.' },
  { id:16, room:'Bathroom', item:'Wash basin', description:['White ceramic wash basin with chrome-coloured mixer tap','Stainless steel kitchen sink with two taps','White plastic utility sink without taps'], condition:['No obvious chips or cracks visible in the basin','Basin has a visible large crack','Tap is visibly missing'], explain:'The basin and mixer tap are visible. Their operation cannot be confirmed from a photo.' },
  { id:17, room:'Bathroom', item:'Shower head', description:['Square overhead shower head with chrome-coloured finish','Round wall mirror with metal frame','Ceiling-mounted extractor fan'], condition:['No obvious external damage visible','Shower head visibly broken off','Heavy limescale clearly covering the spray face'], explain:'This is a square overhead shower head. No obvious external damage is visible; flow was not tested.' },
  { id:20, room:'Hallway', item:'Floor and skirting', description:['Pale wood effect flooring beside white skirting','Cream fitted carpet beside timber trim','Grey ceramic tiles beside metal trim'], condition:['No obvious damage visible along this edge','Flooring visibly torn along this edge','Skirting missing along the wall'], explain:'No damage is visible along the photographed floor and skirting edge.' },
  { id:21, room:'Utility', item:'Ceiling alarm', description:['White circular ceiling-mounted alarm','White pendant light with glass shade','Square wall thermostat'], condition:['No obvious damage visible to the alarm casing','Alarm casing visibly cracked','Alarm missing from its mounting plate'], explain:'The image shows the alarm casing. It does not establish its test result or expiry date.' },
  { id:24, room:'Utility', item:'Washing machine', description:['White front-loading washing machine','White tumble dryer with solid door','Integrated dishwasher with control panel'], condition:['No visible breaks in the photographed door and front','Door glass visibly shattered','Door missing entirely'], explain:'This is a front-loading washing machine. The photo does not establish whether it runs.' },
  { id:25, room:'Bathroom', item:'Bath', description:['White bath with wall-mounted shower hose','White shower tray with sliding doors','Stainless steel sink with drainer'], condition:['No obvious damage visible to the bath surface','Bath visibly cracked through the base','Bath panel missing from the side'], explain:'No chips or cracks are visible on the photographed bath surface. Drain and shower function need testing.' },
  { id:29, room:'Kitchen', item:'Kitchen flooring', description:['Pale wood effect flooring in front of white base units','Dark slate tiles in front of timber units','Cream fitted carpet in front of white units'], condition:['No obvious damage visible in this floor area','Large hole visible in the flooring','Base units visibly detached from the wall'], explain:'The pale wood effect flooring and white base units are visible without a clear defect here.' },
  { id:30, room:'Ceiling', item:'Ceiling alarm', description:['Circular ceiling-mounted smoke alarm','Square ceiling air vent','Recessed spotlight with chrome trim'], condition:['No obvious external damage visible','Alarm visibly detached from ceiling','Casing visibly split open'], explain:'No external damage is visible on the photographed casing. Test result and expiry date need separate evidence.' },
  { id:33, room:'Hallway', item:'Door handle', description:['Silver-coloured lever handle on white painted door','Round brass-coloured knob on timber door','Black pull handle on glazed door'], condition:['No obvious external damage visible to handle or door','Lever visibly snapped off','Door has a large hole around the handle'], explain:'No external damage is visible on the photographed lever. Silver-coloured describes the finish without assuming its material.' },
  { id:2, room:'Hallway', item:'Painted wall', description:['White painted wall beside a dark door frame','White ceramic tile wall beside a bath','Pale wallpaper with a printed pattern'], condition:['Several small dark marks at mid to low level','Large section of plaster missing','Even finish with no visible marks'], explain:'Small dark marks are visible on the white paint. The photo does not show missing plaster.' },
  { id:9, room:'Bedroom', item:'Wardrobe', description:['Dark wardrobe with mirror door and open shelving','White chest of drawers with timber handles','Wall cupboard with glass shelves'], condition:['No visible breaks on the photographed shelves or mirror','Mirror visibly shattered','Upper shelf visibly detached'], explain:'The wardrobe has a mirror and open shelves. No obvious damage is visible on these surfaces.' },
  { id:10, room:'Reception', item:'Framed print', description:['Colourful abstract print in a black frame','Rectangular wall mirror in a silver frame','Unframed landscape photograph'], condition:['No visible break in the photographed frame or print','Glass visibly cracked across the image','Frame missing its upper edge'], explain:'A black-framed abstract print is leaning beside the seating. The photo shows no obvious break.' },
  { id:12, room:'Ceiling', item:'Light fitting', description:['Circular recessed spotlight in a white ceiling','Hanging pendant with a fabric shade','Long fluorescent light fixed to a wall'], condition:['Light is illuminated; no obvious casing damage visible','Fitting hanging loose from the ceiling','Bulb visibly missing'], explain:'The recessed spotlight is illuminated in the photograph. That does not establish long-term function.' },
  { id:18, room:'Hallway', item:'Entrance hall', description:['Pale floor and white painted walls with an internal door','Dark fitted carpet and exposed brick walls','Grey tiled floor with timber panelling'], condition:['No obvious damage visible in this wide view','Large section of flooring visibly missing','Internal door visibly detached'], explain:'The wide shot provides context, but close-ups are still needed before declaring the whole hall unmarked.' },
  { id:19, room:'Hallway', item:'Ceiling lighting', description:['Row of recessed spotlights in a white ceiling','Single pendant light with a fabric shade','Wall-mounted strip lighting only'], condition:['Visible spotlights are illuminated','Every spotlight is visibly unlit','Ceiling has a large hole around the lights'], explain:'The photo shows a row of illuminated recessed lights. It cannot prove the whole circuit is fault-free.' },
  { id:22, room:'Hallway', item:'Door and frame', description:['White painted door with matching frame','Dark timber sliding door with metal track','White glazed door with black frame'], condition:['Two small protrusions or marks visible near the upper door area','Door leaf split from top to bottom','Frame visibly missing'], explain:'The upper door area has two small visible points. Describe their location instead of calling the door perfect.' },
  { id:23, room:'Reception', item:'Open-plan room', description:['Open-plan living and kitchen area with pale floor and grey units','Separate tiled bathroom with white suite','Bedroom with fitted wardrobes and carpet'], condition:['No obvious major damage visible in this wide shot','Several kitchen doors visibly missing','Large hole visible in the floor'], explain:'This is an overview of a living and kitchen area. It gives context but not a full condition check.' },
  { id:27, room:'Kitchen', item:'Integrated appliance', description:['Black glass-fronted integrated oven in kitchen units','White freestanding washing machine','Stainless steel extractor hood'], condition:['No visible break in the photographed front glass','Front glass visibly shattered','Appliance door missing'], explain:'No break is visible in the photographed glass front. Heating function needs testing.' },
  { id:28, room:'Reception', item:'Floor covering', description:['Light fitted carpet beneath a round black table base','Pale wood effect floor beneath a chair','Grey ceramic tiles beneath a black table'], condition:['No visible tear in the photographed carpet immediately around the base','Carpet has a large torn hole','Heavy staining covers the photographed carpet'], explain:'The dark circle is the table base. No carpet tear is visible immediately beside it; wider carpet condition needs more views.' },
  { id:31, room:'Bedroom', item:'Painted wall', description:['White painted wall beside a corner','Grey tiled shower wall','Cream fabric curtain beside a window'], condition:['Small dark marks visible on the painted surface','Large area of paint peeling away','No visible marks at all'], explain:'There are small dark marks on the white wall. Avoid upgrading them to major damage.' },
  { id:32, room:'Reception', item:'Coffee table', description:['Low dark rectangular coffee table with lower shelf','Tall glass dining table with four chairs','White bedside cabinet with drawers'], condition:['Top has light visible marks; no break is obvious','Table top is split in two','One table leg is visibly absent'], explain:'The low dark table has visible light marks on its top. The image does not show a structural break.' },
  { id:34, room:'Bedroom', item:'Open storage', description:['White open shelving alcove beside a door frame','Dark freestanding wardrobe with mirror','White ceramic shower tray'], condition:['No obvious damage visible on the shelf or side panels','Shelf visibly collapsed','Rear panel has a large hole'], explain:'No damage is visible on the photographed shelf and side panels. Unseen areas remain unverified.' },
  { id:35, room:'Hallway', item:'Wall corner', description:['White painted wall corner above pale flooring','Grey tiled bathroom corner above a bath','Timber panelled corner above carpet'], condition:['No obvious major damage visible in this narrow view','Large crack running down the corner','Skirting missing across the entire wall'], explain:'The photo shows a narrow painted wall corner. Keep the condition limited to what the view reveals.' },
  { id:36, room:'Bedroom', item:'Window handle', description:['White window frame with a white lever handle and keyhole','Timber window frame with a brass-coloured round knob','White door with a chrome-coloured pull handle'], condition:['No obvious damage visible to the handle in this view','Handle visibly snapped off','Window glass visibly cracked'], explain:'The white lever handle and keyhole are visible. The image cannot show whether the lock or window operates.' },
  { id:37, room:'Kitchen', item:'Built-in oven', description:['Black glass-fronted built-in oven beneath a metal gas hob','White freestanding microwave above a ceramic hob','Stainless steel dishwasher beneath a sink'], condition:['No obvious break visible on the oven front','Oven door glass visibly shattered','Oven door missing from the cabinet'], explain:'The oven front and hob are visible. Power, heating and burner operation need separate checks.' },
  { id:38, room:'Bedroom', item:'Window sill', description:['White painted internal window sill and reveal','Unpainted timber skirting board beside a door','White ceramic bath surround'], condition:['Paint peeling and cracking along the front edge of the sill','No visible marks or paint defects','Sill visibly detached from the wall'], explain:'Paint is visibly flaking along the front edge of the sill, with fine cracks on its top. State the location rather than guessing the cause.' },
  { id:39, room:'Living area', item:'Floorboards', description:['Pale timber floorboards beside a white skirting board','Grey fitted carpet beside a metal threshold','Brown ceramic floor tiles beside a cabinet'], condition:['No obvious damage visible across the photographed boards','Several boards visibly missing','A wide split runs through the centre of every board'], explain:'Pale timber boards and white skirting are visible. This photo does not establish the condition of the rest of the floor.' },
  { id:40, room:'Bedroom', item:'Window reveal', description:['White painted window reveal around frosted glazing','Grey tiled shower wall beside clear glazing','Bare timber frame around a mirror'], condition:['Small marks visible near the lower frame and corner','A large section of plaster missing','Window pane visibly shattered'], explain:'There are small marks near the lower frame and corner. The photo cannot establish whether the glass or frame seals are sound.' }
];

// These rounds give facts that a single photograph cannot establish. They are
// explicitly marked as check-out or evidence scenarios and never imply liability.
export const scenarios = [
  { id:'s1', image:'/assets/photos/16.webp', room:'Bathroom', item:'Tap', prompt:'What belongs in the check-out report?', descLabel:'1 · Check-out tag', conditionLabel:'2 · Factual note', scenario:'At check-out, you see this tap actively dripping into the basin. The inventory baseline recorded no leak.', description:['Maintenance','Review','No tag; ignore it'], condition:['Tap actively dripping into basin during check-out; maintenance attention required','Tenant caused a leak and must pay','Tap may be broken because the basin looks wet'], explain:'An observed active leak is Maintenance. Record what happened, not who caused it.' },
  { id:'s2', image:'/assets/photos/31.webp', room:'Bedroom', item:'Wall', prompt:'Choose the tag and wording.', descLabel:'1 · Check-out tag', conditionLabel:'2 · Factual note', scenario:'At check-out, a new water mark is visible on the wall. No water is actively dripping, and the cause is unknown.', description:['Review','Maintenance because any mark proves a leak','No tag because water marks are cleaning'], condition:['Water mark on the photographed wall; no active dripping observed','Tenant caused damp and owes repairs','Active pipe leak confirmed behind wall'], explain:'An unexplained water mark calls for Review. It does not establish an active leak or liability.' },
  { id:'s3', image:'/assets/photos/24.webp', room:'Utility', item:'Washing machine', prompt:'How should you report the power check?', descLabel:'1 · Check-out tag', conditionLabel:'2 · Factual note', scenario:'At check-out, this washing machine does not power on during your attempt. The wall switch and fuse board have not been checked.', description:['Review','Maintenance because the motor is definitely broken','Item(s) not located'], condition:['No power observed during attempted test; cause and operation unconfirmed','Motor failed and requires replacement','Machine is in full working order'], explain:'Use Review for an appliance without power when the cause is unverified. Do not diagnose the motor from one attempt.' },
  { id:'s4', image:'/assets/photos/10.webp', room:'Reception', item:'Framed print', prompt:'What should the check-out say?', descLabel:'1 · Check-out tag', conditionLabel:'2 · Factual note', scenario:'The inventory baseline lists this framed print. At check-out it cannot be found after searching the property.', description:['Item(s) not located','Maintenance','Review for general wear'], condition:['Listed framed print not located during check-out search','Tenant stole the framed print','Print was broken and thrown away'], explain:'Use Item(s) not located when a baseline item cannot be found. This does not assign liability.' },
  { id:'s5', image:'/assets/photos/5.webp', room:'Bedroom', item:'Sofa cushion', prompt:'Does this change need a tag?', descLabel:'1 · Check-out tag', conditionLabel:'2 · Factual note', scenario:'At check-out, a baseline comparison shows only light general wear on this cushion. No significant change is documented.', description:['No tag for general wear','Maintenance','Item(s) not located'], condition:['Light surface wear on photographed cushion; record in condition text','Tenant deliberately damaged the cushion','Cushion must be replaced immediately'], explain:'General wear is described in the report but is not a check-out tag. No cause or liability is inferred.' },
  { id:'s6', image:'/assets/photos/14.webp', room:'Bathroom', item:'Basin', prompt:'Can you grade the whole property from this?', descLabel:'1 · Cleaning decision', conditionLabel:'2 · Accurate statement', scenario:'This basin looks clean in the photo. You have not inspected the rest of the property.', description:['Record the local observation; defer the whole-property cleaning grade','Mark the entire property professionally cleaned','Mark the whole property dirty'], condition:['No visible residue on the photographed basin; overall cleaning standard not yet assessed','Professionally cleaned throughout the property','Tenant definitely cleaned this basin'], explain:'Cleaning summaries cover the whole property. One clean basin cannot prove a professional clean or identify who cleaned it.' },
  { id:'s7', image:'/assets/photos/23.webp', room:'Kitchen', item:'Overview', prompt:'What evidence is still missing?', descLabel:'1 · Next evidence', conditionLabel:'2 · Why it matters', scenario:'You have only this wide kitchen overview photo. The supplied company checklist requires detailed photographic evidence.', description:['Photograph cupboard interiors and appliance details','Stop: one wide shot proves every item condition','Take another photo of the same ceiling only'], condition:['The overview cannot show interior units or appliance model and serial details','The overview proves every cupboard is empty','The overview establishes each appliance is working'], explain:'The supplied company checklist asks for room corners, cupboard interiors, appliance details, sanitary ware, vents, marks, keys, alarms and meters where relevant.' },
  { id:'s8', image:'/assets/photos/30.webp', room:'Ceiling', item:'Alarm', prompt:'What should you capture next?', descLabel:'1 · Next evidence', conditionLabel:'2 · Why it matters', scenario:'You have a wide photo of the ceiling alarm, but no close-up of its label or test result.', description:['Capture readable expiry details where applicable and record the test separately','State that it passed because the casing is clean','Skip the alarm because it is visible'], condition:['A clean-looking casing cannot establish expiry or function','Any visible alarm is automatically in date','The photograph proves the alarm sounds'], explain:'The company checklist calls for alarm evidence including expiry dates where applicable. Function needs an actual test record.' },
  { id:'s9', image:'/assets/photos/6.webp', room:'Kitchen', item:'Wall cupboard', prompt:'What order completes this item?', descLabel:'1 · Report order', conditionLabel:'2 · Missing evidence', scenario:'You photographed this cupboard exterior and open shelves. The cupboard contents have not been checked.', description:['Exterior, interior, then contents','Contents only; exterior can be skipped','Exterior only; open doors prove contents'], condition:['Record the visible interior surfaces, then list and photograph contents found inside','Assume the cupboard is empty from this angle','Call the hidden contents undamaged'], explain:'The supplied cheat sheet uses exterior, interior, contents order. An exterior image alone cannot establish interior condition or contents.' },
  { id:'s10', image:'/assets/photos/33.webp', room:'Hallway', item:'Keys', prompt:'Which key note is complete?', descLabel:'1 · Key record', conditionLabel:'2 · Missing-detail check', scenario:'Fictional scenario: you collected two front-door keys and one entry fob from the concierge, then returned all three to the concierge.', description:['Two front-door keys and one entry fob collected from and returned to concierge','Three keys received and put back somewhere','Front door unlocked; key details unnecessary'], condition:['Count, type, use, and return recipient are stated','The door photo proves how many keys were returned','A key photo alone establishes the recipient'], explain:'The supplied cheat sheet asks for key count, type, use and recipient or return destination. These facts come from the scenario, not the door photo.' }
];

// Each slot is a visible part of the report. Correct choices are first and are
// shuffled for each match, just like the existing question options.
export const mixQuestions = [
  { id:'m1', room:'Hallway', item:'Door handle', image:'/assets/photos/33.webp', prompt:'Build the most accurate door handle description.', slots:[
    {label:'Colour',options:['White','Black','Brown']},
    {label:'Finish',options:['Painted','Bare timber','Tiled']},
    {label:'Item',options:['Door','Cupboard','Window']},
    {label:'Handle finish',options:['Silver-coloured','Brass-coloured','Black']},
    {label:'Handle type',options:['Lever handle','Round knob','Pull handle']}
  ], explain:'The photo shows a white painted door with a silver-coloured lever handle. Describe the visible finish rather than assuming the handle is chrome.' },
  { id:'m2', room:'Bathroom', item:'Wash basin', image:'/assets/photos/16.webp', prompt:'Assemble the visible basin report.', slots:[
    {label:'Colour',options:['White','Black','Grey']},
    {label:'Material',options:['Ceramic','Stainless steel','Timber']},
    {label:'Item',options:['Wash basin','Kitchen sink','Bath']},
    {label:'Tap finish',options:['Chrome-coloured','Brass-coloured','Black']},
    {label:'Tap type',options:['Mixer tap','Two separate taps','No tap visible']}
  ], explain:'A white ceramic basin and chrome-coloured mixer tap are visible. The photo cannot confirm that the tap works.' },
  { id:'m3', room:'Bedroom', item:'Painted wall', image:'/assets/photos/31.webp', prompt:'Build a precise wall observation.', slots:[
    {label:'Colour',options:['White','Grey','Blue']},
    {label:'Surface',options:['Painted','Tiled','Wallpapered']},
    {label:'Item',options:['Wall','Door','Ceiling']},
    {label:'Condition',options:['Small dark marks','Large missing plaster area','No marks visible']},
    {label:'Location',options:['Near the corner','Across the whole wall','On the floor']}
  ], explain:'Small dark marks are visible on the white painted wall near the corner. Avoid claiming major damage.' }
];
